env: default
server:
  port: 8080
spring:
  banner:
    image:
      location: hacker.png

domain: michalszalkowski.com

themes: WHITE,BLUE

admin:
  email: admin@michalszalkowski.com
  phone: 000-111-111