spring:
  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      url: jdbc:mariadb://localhost:3306/posejdon
      username: root
      password: toor
      driver-class-name: org.mariadb.jdbc.Driver